kindnesswebsite/website/views.py
### pages of the website
# from operator import methodcaller
# from numpy import result_type
# import pandas as pd
from email.policy import default
from urllib import response
from flask import Blueprint, flash, jsonify, render_template, request, redirect, Markup, session, abort
# import os
from flask_login import login_required, current_user

from website.chatbot.chat import get_response
from . import db
from .models import Aok, NonAok, ScrapperSentence, User, WebsiteScrapper
import json
from .control import canScrap, checkIfAoK, doesAoKExist, getBaseURL, getModelsInfo, getRobotsURL, getSentenceFromDB, getSiteMaps, populateDatabaseWithAoKs, populateDatabaseWithNonAoKs, populateModelTable, removeFromSentences,  scrapWebsite, addAoK
# import website
from werkzeug.security import generate_password_hash
from flask_login import login_user


views = Blueprint("views", __name__)

# file_name = './website/static/actsOfKindness.xlsx'
# # file_name = 'actsOfKindness.xlsx'
# sheet_name = 'All_AoKs'
# description_column = 'Description'
# websiteURL = ""

# the route of our website
@views.route('/', methods=['GET', 'POST'])
def home():
    
    myEmail="faeq.rimawi@gmail.com"
     #add user to databse
    if User.query.filter_by(email=myEmail).first() is None: 
        new_user = User(email=myEmail, first_name="faeq", password=generate_password_hash("asd12345", method='sha256'))
        db.session.add(new_user)
        db.session.commit()
        login_user(new_user, remember=True)
    
    populateModelTable()
    populateDatabaseWithAoKs()
    populateDatabaseWithNonAoKs()  
        
                
    return render_template("home.html", user=current_user)


# the route of our website
@views.route('/chatbot', methods=['GET', 'POST'])
def chatbot():
    
    if request.method == 'POST':
        text = request.get_json().get("message")
        
        #TODO: check if text is valid
        
        responses = get_response(text)
        message = {"answers": responses}
        
        print("@@@ ", message)
        return jsonify(message)
        
            
    return render_template("chatbot.html", user=current_user)


@views.route('/guessAoK', methods=['POST', 'GET'])
def guessAoK():

    if request.method == 'POST':
        act = request.form.get('act')
        
        if act:
           probability = checkIfAoK(act)
        #    d =  jsonify(prob=probability) 
        #    return d   
           return render_template('guessAoK.html', user=current_user, prob=probability, act=act)
        else:
            flash("Please enter an act", category='error')

            
    return render_template("guessAoK.html", user=current_user, prob=-1, act="")


@views.route('/edit', methods=['GET', 'POST'])
def editAoK():
    
    if request.method == 'POST':
        aok = request.form.get('aok')
        
        if len(aok)<1:
            flash("Act too short!", category='error')
            
        else:
            new_aok = Aok(act=aok, user_id=current_user.id)
            db.session.add(new_aok)
            db.session.commit()
            
            flash("Act added successfully", category='success')
            
    return render_template("editAoK.html", user=current_user)



@views.route('/listofAoK')
def listofAoK():
 
    # testModelTable()
    # populateDatabase()
    
    
    # df = pd.read_excel(file_name, sheet_name=sheet_name, usecols=[description_column])
    aoks = Aok.query.all()
    nonaoks = NonAok.query.all()
    return render_template("listofAoK.html", aoks=aoks, nonaoks=nonaoks, user=current_user)
    # return df.to_html()
 
 
@views.route('/api/aokdata', methods=["POST"])
def aokdata():
   
    #  return {'data': [aok.to_dict() for aok in Aok.query]}
    query = Aok.query
    data = request.get_json()
    
    if 'operation' not in data:
        abort(400) 

    operation = data['operation']
    
    match operation:
        case 'fetch-all':
            return [aok.to_dict() for aok in query]

        case _:
            print("@@@ nothing")
            return []
       
       
@views.route('/api/nonaokdata', methods=['POST'])
def nonaokupdate():
    
    query = NonAok.query
    data = request.get_json()
    
    if 'operation' not in data:
        abort(400) 

    operation = data['operation']
    
    match operation:
        case 'fetch-all':
            return [nonaok.to_dict() for nonaok in query]
        case _:
            return []

      
@views.route('/api/actdata', methods=['POST'])
def actdataupdate():
    
    data = request.get_json()
    query = ScrapperSentence.query
     
    if 'operation' not in data:
        abort(400)
    
    operation = data['operation']    
    
    
    match operation:
        case 'fetch-all':
            website = data['data']  
            if website:
             
    
                websiteID = WebsiteScrapper.query.filter_by(url=str(website)).first()
                
                if websiteID:
            
                    return [sent.to_dict() for sent in query.filter_by(website_id=websiteID.id)]
                else:
                    return [] 
        case 'updateAct':
            oldAndNewAct = data['data']
            if len(oldAndNewAct) <2:
                return ''
            
            oldAct = oldAndNewAct[0]
            newAct = oldAndNewAct[1]
            
            field = 'text'
            sentences = query.filter_by(text=str(oldAct)).all()
            for sent in sentences:
                setattr(sent, field, newAct)
                db.session.commit()
            
            return jsonify({"response": "success"})
        
        case 'removeAct':
            actID = data['data']
            print("delete id ", actID)
            if actID is None:
                return jsonify({})
            
            act = query.get(int(actID))
            
            
            
            if act is None:
                return jsonify({})
            
            db.session().delete(act)
            db.session.commit()
            return jsonify({"response": "success"})
            
           
           
@views.route('/delete-AoK', methods=['POST'])
def delete_AoK():
    aok = json.loads(request.data)
    aokId = aok['aokId']      
    
    aok = Aok.query.get(aokId)
    if aok.user_id == current_user.id:
        db.session().delete(aok)
        db.session.commit()
        
    return jsonify({})


@views.route('/add-AoK', methods=['POST'])
def add_AoK():

    sent = json.loads(request.data)
    sentID = sent['actID']   
    # websiteURL = aok['websiteURL']
    
    # if type(sentStr) != str:
    #     sentStr = str(sentStr)
          
    sent = getSentenceFromDB(sentID)
        
    if sent is None:        
        return jsonify({'message':'error'})
                    
    # check if already exists in the database
    inDB = doesAoKExist(sent.text)
    
    if inDB:
        result = jsonify({'message':'exists'})
    
        return result
    else: 
        result = addAoK(sent.text, sent.get_website()) 
        
      
        if result is not None:
            removeFromSentences(sent.text)
            res = {'message':'added'} 
            return jsonify(res)
        else:
            return jsonify({'message':'error'})


@views.route('/update-prob', methods=['POST'])
def update_prob():
     aok = json.loads(request.data)
     aok_str = aok['aok']
     
     if type(aok_str) != str:
        aok_str = str(aok_str)
        
     prob = checkIfAoK(aok_str)  
     
     return jsonify({'prob':prob}) 
        
        
    
    
@views.route("/aok-scrapper", methods=["POST", "GET"])
def aokScrapper():
    
    if request.method == 'POST':
     
        websiteURL = request.form.get('websiteURL')  
               
      
        sents =  scrapWebsite(websiteURL)
      
        # acts_and_probs = {'data': [{"sents":"1"}, {"sents":"1"}],
        # 'total': len(sents),
        # }
      
        #get sitemap
        sitemap = {'sitemap':getSiteMaps(websiteURL)}
     
    
        # return render_template("scrapper.html", user=current_user, websiteURL=websiteURL, act_probs=act_probs, canScrap=True)
        isPer = canScrap(websiteURL)
        
        robotUrl = getRobotsURL(websiteURL)
        baseURL = getBaseURL(websiteURL)
        if not isPer:
           flash(Markup("Scraping may not be permissible on this webpage per the website's permissions. For more info, see: <a href=\""+robotUrl+"\" target='_blank' class=\"alert-link\">"+robotUrl + "</a>") , category='warning')
            
     
        return render_template("scrapper.html", user=current_user, websiteURL=websiteURL, robotsURL=robotUrl, baseURL=baseURL, sitemap=sitemap) 
    
    # get all sites already visited
    siteURLs = [url.url for url in WebsiteScrapper.query.all()]
    print("@@@@ ", siteURLs)
    return render_template("scrapper.html", user=current_user)



@views.route("/aok-model", methods=["POST", "GET"])
def AoKModel():
    
    info = getModelsInfo()
    
    return render_template("AoKModel.html", user=current_user, models=info)
  
  
    
@views.get("/toggle-theme")
def toggle_theme():
    current_theme = session.get("theme")
    if current_theme == "dark":
        session["theme"] = "light"
    else:
        session["theme"] = "dark"

    return redirect(request.args.get("current_page"))


             
    
       
    
# @views.route('/api/actdata')
# def actdata():
   
#     #  return {'data': [aok.to_dict() for aok in Aok.query]}
#     query = ScrapperSentence.query
    
#     website = request.args.get('website')
#     websiteID = WebsiteScrapper.query.filter_by(url=website)
    
#     print(" @@@", website, " id ", websiteID)

#     return [sent.to_dict() for sent in query.filter_by(url_id=websiteID)]

#    # search filter
#     search = request.args.get('search')
#     if search:
#         query = query.filter(db.or_(
#             ScrapperSentence.text.like(f'%{search}%')
            
#         ))
#     total = query.count()

kindnesswebsite/website/templates/AoKModel.html
{% extends 'base.html' %} 

{% block title %}AoK Model{% endblock %}


{% block content %}

<br/>
<h2 align="center"> NLP  Models for Kindness </h2>
<br/>

<table id="models" class="table table-striped">
    <thead>
        <tr>
        <th>Description</th>
        <th># of AoKs</th>
        <th># of Non-AoKs</th>
        </tr>
    </thead>
    <tbody> 
    
    {% if  models %}
    {% for model in models %}
    <tr>
        <td>{{model[0]}}</td>
        <td>{{model[1]}}</td>
        <td>{{model[2]}}</td>
    </tr>
    
    {% endfor %}
    
    </tbody>
    </table>
    {% endif %}
  
{% endblock %}

kindnesswebsite/website/templates/base.html
{% from "macros/svgs.html" import moon, sun %}

<!DOCTYPE html>


<html lang="en" class="{{ 'dark-mode' if session.get('theme') == 'dark' }}">

<head>
     <meta charset="utf-8" />
     <meta name="viewport" content="width=device-width, initial-scale=1" />

   <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />

    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.25/css/dataTables.bootstrap5.css">

    <link rel="stylesheet" type="text/css" href="{{url_for('static', filename='styles/base.css')}}">

    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      crossorigin="anonymous"
    />

    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">


    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.png') }}">

    <script src="https://kit.fontawesome.com/e03887fb7f.js" crossorigin="anonymous"></script>

    <link href="https://unpkg.com/gridjs/dist/theme/mermaid.min.css" rel="stylesheet" />
    <script src="https://unpkg.com/gridjs/dist/gridjs.umd.js"></script>

    <script src="https://unpkg.com/ag-grid-community/dist/ag-grid-community.min.noStyle.js"></script>
    
    <link rel="stylesheet"
    href="https://unpkg.com/ag-grid-community/styles/ag-grid.css"/>

    <link rel="stylesheet"
    href="https://unpkg.com/ag-grid-community/styles/ag-theme-alpine.css"/>

    {% block  header %}{% endblock  %}

    <!--
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.2/jquery.min.js"></script>
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.css">
    <script type="text/javascript" src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.js"></script>
    -->

    <title>{% block title %}kindnessBase{% endblock %}</title>

</head>

<body>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbar">
        <div class="navbar-nav">
          {% if user.is_authenticated %} 
          <a class="nav-item nav-link" id="home" href="/">Home</a>
          <a class="nav-item nav-link" id="guessAoK" href="/guessAoK">Guess</a>
          <a class="nav-item nav-link" id="listofAoK" href="/listofAoK">List</a>
          <a class="nav-item nav-link" id="edit" href="/edit">Edit</a>
          <a class="nav-item nav-link" id="aok-scrapper" href="/aok-scrapper">Scrap</a>
          <a class="nav-item nav-link" id="aok-model" href="/aok-model">Models</a>
          <a class="nav-item nav-link" id="chatbot" href="/chatbot">Chatbot</a>
          <a class="nav-item nav-link" id="logout" href="/logout">Logout</a>
          {% else %}
          <a class="nav-item nav-link" id="home" href="/">Home</a>
          <a class="nav-item nav-link" id="guessAoK" href="/guessAoK">Guess</a>
            <a class="nav-item nav-link" id="login" href="/login">Login</a>
           <!-- <a class="nav-item nav-link" id="sign-out" href="/sign-up">Sign Up</a>
            <!-- <a class="nav-item nav-link" id="sign-out" href="/sign-up">Sign Up</a>-->
          {% endif %}
          
        </div>
    </div>

</nav>

{% with messages = get_flashed_messages(with_categories=true) %}
  {% if messages %}
    {% for category, message in messages %}
    
    {% if category == 'error' %}
      <div class="alert alert-danger alert-dismissable fade show" role="alert">
      {{message}}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
      </div>
      {% endif %}
      
      {% if category == 'warning' %}
      <div class="alert alert-warning alert-dismissable fade show" role="alert">
      {{message}}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
      </div>
      {% endif %}

      {% if category=='success' %}  
      <div class="alert alert-success alert-dismissable fade show" role="alert">  
        {{message}}
        <button type="button" class="close" data-dismiss="alert">
          <span aria-hidden="true">&times;</span>
        </button>
        </div>
        {% endif %}
    {% endfor %}
  {% endif %}
{% endwith %}

<div class="container">
{% block content%}
{% endblock %}
</div>



 <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>
  

 
<!--
  script type="text/javascript">$(document).ready(function(){$('table').DataTable({"pageLength": 50});});
</script>
-->


    <script
      type="text/javascript"
      src="{{ url_for('static', filename='js/index.js') }}"
    ></script>

    <script type="text/javascript" charset="utf8" src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.25/js/jquery.dataTables.js"></script>
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.25/js/dataTables.bootstrap5.js"></script>

{% block scripts %}{% endblock %}

</body>
</html>

kindnesswebsite/website/templates/chatbot.html
{% extends 'base.html' %}
{% block title %}Chatbot{% endblock  %}

{% block header %}
<link rel="stylesheet" type="text/css" href="{{url_for('static', filename='styles/chatbot.css')}}">
{% endblock %}

{% block  content%}


<div class="chatbox" style="width: 60%; height: 60%;">
    <div class="chatbox__support" style="width: 100%; height: 100%;">

        <div class="chatbox__header">
            <div class="chatbox__image--header">
                <img src="https://img.icons8.com/color/48/000000/circled-user-female-skin-type-5--v1.png" alt="image">
            </div>

            <div class="chatbox__heading--header">
                Eleos
              </div>

            <div class="chatbox__content--header">
        
            </div>
        </div>

        <div class="chatbox__messages" >
            <div></div>
        </div>
        <div class="chatbox__footer">
            <input type="text" placeholder="Write a message...">
            <button class="chatbox__send--footer send__button">Send</button>
        </div>
    </div>
    <div class="chatbox__button">
        <button><img src="{{ url_for('static', filename='images/chatbox-icon.svg') }}" /></button>
    </div>
</div>

<div class="create"></div>

{% endblock  %}


{% block scripts  %}

<!--<script>
    $SCRIPT_ROOT = {{ request.script_root|tojson }};
</script>-->
<script type="text/javascript" src="{{ url_for('static', filename='js/chatbot.js') }}"></script>

{% endblock  %}

kindnesswebsite/website/templates/editAoK.html
{% extends 'base.html' %} 
{% block title %}Edit AoKs{% endblock%}
{% block content%}

<br/>
<h1>Add Acts of Kindness</h1>

<form method='POST'>
<textarea name="aok" id='aok' class='form-control'></textarea>
<br/>
<div align='center'>
<button type="submit" class="btn btn-primary">Add AoK</button>
</div>
</form>

<br/>
<br/>
<ul class="list-group list-group-flush" id="aoks">
    {% for aok in user.acts %} 
    <li class="list-group-item">{{aok.act}}
        <button type="button" class="close" onClick="delete_AoK({{aok.id}})">
            <span aria-hidden="true">&times;</span>
        </button>
    </li>
    {% endfor%}


{% endblock%}

kindnesswebsite/website/templates/guessAoK.html
{% extends 'base.html' %} 
{% block title %}Guess if AoK{% endblock%}


{% block content%}

<br/>

<form method="POST" name="aok-form">
<h3 align>Is my Act an Act of Kindness (AoK)?</h3>

<input type="text" class="form-control" id="act" name="act" placeholder="Enter Act Description"/>

<br/>

<button type="submit" class="btn btn-primary" >Guess</button>

</form>



<!--
<script type="text/javascript">
    (uri => {
      // Register a listener for submit events.
      const form = document.querySelector('form[name="aok-form"]');
      form.addEventListener('submit', evt => {
        // Suppress the default behavior of the form.
        evt.preventDefault();
        console.log("###### submitting")
        // Submit the form data.
        fetch(uri, {
          method: 'post',
          body: new FormData(evt.target)
        }).then(resp => resp.json())
          .then(data => {
            console.log("#######" + data);
            // Handle response here.
            var prob2 = prob
            var element = document.getElementById("lbl-prob")
            // const prob = JSON.parse(data)
            //console.log("prooob: " + prob)
            
          });
        // Reset the form.
        evt.target.reset();
      });
    })({{ url_for('views.guessAoK') | tojson }});
  </script>
-->
<br/>


<div>
    <label for="prob" id="lbl-prob">

        {% if prob >= 0 %}
        
        <h3>Probability: {{"{:.2f}".format(prob) + "%"}}</h3>

        {% endif %}
    </label>
</div>


{% endblock%}

<!--
{% block script %}

<script type="text/javascript">
  (uri => {
    // Register a listener for submit events.
    const form = document.querySelector('form[name="aok-form"]');
    form.addEventListener('submit', evt => {
      // Suppress the default behavior of the form.
      evt.preventDefault();
      
      // Submit the form data.
      fetch(uri, {
        method: 'post',
        body: new FormData(evt.target)
      }).then(resp => resp.json())
        .then(data => {
          console.log("#######" + data);
          // Handle response here.
          var prob2 = {{prob | tojson}}
          console.log(prob2)
          
          // const prob = JSON.parse(data)
          //console.log("prooob: " + prob)
          
        });
      // Reset the form.
      evt.target.reset();
    });
  })({{ url_for('views.guessAoK') | tojson }});
</script>

<script>
  $("#aok-form").on("submit",function(e){
      e.preventDefault();
      $.ajax({
          url : '/guessAok',
          type: "POST",
          data: $(this).serialize(),
          success: function (data) {
            
              window.location.href = '/guessAok' + data.id;
             
          },
          error: function (jXHR, textStatus, errorThrown) {
            alert(errorThrown);
          }
      });
  });
  </script>

{% endblock  %}
-->

kindnesswebsite/website/templates/home.html
{% extends 'base.html' %} 
{% block title %}HOME{% endblock%}


{% block content%}

<br/>
<h1>Welcome to Kind Computing</h1>



{% endblock%}

kindnesswebsite/website/templates/listofAoK.html
{% extends 'base.html' %} 
{% block title %}Acts of Kindness{% endblock%}

{% block header %}
<link rel="stylesheet" type="text/css" href="{{url_for('static', filename='styles/listofAoK.css')}}">
<script type="text/javascript" src="{{ url_for('static', filename='js/listofAoK.js') }}"></script>
{% endblock %}


{% block content%}

<br/>

<h2 align="center">Database Acts</h2>
<br/>

<div class="collapsible" id="div-kindness" >
      
    <b>Acts of Kindness</b>
   
</div>


<div class="content" id="aoks">

  <div id="myGrid" class="ag-theme-alpine" style="height:700px; padding-top:10px;"></div>

</div>


<br/><br/>


<div class="collapsible" id="div-nonkindness" >
      
    <b>Non-Kindness Acts</b>
   
</div>


<div class="content" id="nonaoks">

  <div id="nonAokmyGrid" class="ag-theme-alpine" style="height:700px; padding-top:10px;"></div>

</div>
<!--<br/>
<table id="nonaoks" class="table table-striped">
<thead>
    <tr>
    <th>#</th>
    <th>Description</th>
    <th>Source</th>
    <th>Date Added</th>
    </tr>
</thead>
<tbody> 

{% for nonaok in nonaoks %}
<tr>
    <th scope="row">{{ loop.index }}</th>
    <td>{{nonaok.act}}</td>
    <td>{{nonaok.source}}</td>
    <td>{{nonaok.date}}</td>
</tr>
{% endfor %}

</tbody>
</table>-->



{% endblock%}


{% block scripts %}

<script>
    var coll = document.getElementsByClassName("collapsible");
    var i;
    
    for (i = 0; i < coll.length; i++) {
      coll[i].addEventListener("click", function() {
        this.classList.toggle("active");
        var col2 = document.getElementsByClassName("collapsible");

        var content = this.nextElementSibling;
        if (content.style.maxHeight){
          content.style.maxHeight = null;
        } else {
          content.style.maxHeight = content.scrollHeight + "px";
        } 
      });
    }
    </script>



<script>
    $(document).ready(function(){

      fillAoKsGrid();
      fillNonAoKsGrid();
             /* $('#aoks').DataTable({
                ajax: '/api/data',
                serverSide: true,
                columns: [
                  {data: 'act'},
                  {data: 'source'},
                  {data: 'date'}
                  //{data: 'phone', orderable: false},
                //  {data: 'email'}
                ],
              });
           

       // $('#aoks').DataTable({

        //});

        $('#nonaoks').DataTable({

        });*/
    });
</script>
{% endblock %}

kindnesswebsite/website/templates/login.html
{% extends 'base.html' %} 
{% block title %}Login{% endblock%}


{% block content%}

<br/>
<form method="POST">
<h3 align="center">Login</h3>

<div class="form-group">
    <label for="email">Email Address</label>
    <input type="email" class="form-control" id="email" name="email" placeholder="Enter email"/>
</div>


<div class="form-group">
    <label for="password1">Password</label>
    <input type="password" class="form-control" id="password1" name="password1" placeholder="Enter password"/>
</div>

<br/>

<button type="submit" class="btn btn-primary">Login</button>

</form>
{% endblock%}

kindnesswebsite/website/templates/sing_up.html
{% extends 'base.html' %} 
{% block title %}Sign Up{% endblock%}


{% block content%}

<br/>
<form method="POST">
<h3 align="center">Sing Up</h3>

<div class="form-group">
    <label for="email">Email Address</label>
    <input type="email" class="form-control" id="email" name="email" placeholder="Enter email"/>
</div>

<div class="form-group">
    <label for="firstName">First Name</label>
    <input type="text" class="form-control" id="firstName" name="firstName" placeholder="Enter First Name"/>
</div>

<div class="form-group">
    <label for="password1">Password</label>
    <input type="password" class="form-control" id="password1" name="password1" placeholder="Enter password"/>
</div>

<div class="form-group">
    <label for="password2">Confirm</label>
    <input type="password" class="form-control" id="password2" name="password2" placeholder="Password (confirm)"/>
</div>

<br/>

<button type="submit" class="btn btn-primary">Submit</button>

</form>
{% endblock%}